{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import dash_table as dt\n",
    "import pandas as pd\n",
    "\n",
    "from plotly import graph_objs as go\n",
    "from plotly.graph_objs import *\n",
    "from dash.dependencies import Input, Output, State"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1944, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\flask\\app.py\", line 1992, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1318, in _setup_server\n",
      "    self._validate_layout()\n",
      "  File \"C:\\Users\\hpzju\\Anaconda3\\envs\\ds\\lib\\site-packages\\dash\\dash.py\", line 1295, in _validate_layout\n",
      "    'The layout was `None` '\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.\n"
     ]
    }
   ],
   "source": [
    "app = dash.Dash(__name__)\n",
    "server = app.server\n",
    "app.title = 'NYC Wi-Fi Hotspots'\n",
    "\n",
    "app.run_server(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# -*- coding: utf-8 -*-\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
